apiVersion: v1
kind: ImageStream
metadata:
  name: openshift-acme
  labels:
    app: openshift-acme
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/mnairn/openshift-acme:latest
    importPolicy:
      scheduled: true
